# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTableView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SDWebImage', '~> 4.0'
pod 'WYPopoverController', '~> 0.2.2'
pod 'GSKStretchyHeaderView'

  # Pods for DemoTableView

  target 'DemoTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoTableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
